### ISSUE TITLE
Structure the database

### ISSUE THREAD

**Issue by DamianKobylinski** [knmlprz/CASSINI-2024-DELETE#6]
# Task conditions

- [ ] create json file with structure for the project - which parameters we should use
- [ ] make final structure of using parameters
- [ ] test - fetching datas from json file  eg. infrastrure[1].capacity -> 5

# Nice to read

https://www.w3schools.com/js/js_json_intro.asp

https://www.youtube.com/watch?v=0kHFDV1lAuI&ab_channel=AustinDavis
